extends Node

const WORLD_LAYER_BIT = 0
const PLAYER_LAYER_BIT = 1
const PLAYER_HURTBOX_LAYER_BIT = 2
const ENEMY_HURTBOX_LAYER_BIT = 3
const ITEM_LAYER_BIT = 4
const ENEMY_LAYER_BIT = 5
const SOFT_COLLISION_LAYER_BIT = 6
const PLAYER_PICKUP_LAYER_BIT = 7
const ITEM_PICKUP_LAYER_BIT = 8
const GATHERABLE_ITEM_LAYER_BIT = 9
